### ISSUE TITLE
dm command not triggering

### ISSUE THREAD

**Issue by department19** [fac30/discord_chatbot_Elena_Jack#19]
![image](https://github.com/fac30/discord_chatbot_Elena_Jack/assets/129791671/44d0cf8a-30d4-4389-928d-264529ebf546)
the conditional in `line 162` is essentially blocking the progression of the complier to reach the code that will trigger the dm command that is in `line 166`

- need to alter so that the dm command can be triggered along with other commands

**Comment by 3le81** [comment]
Dm code fixed with async/await function, now all the commands get executed. closing the issue
